# Generated by Django 3.0.4 on 2020-03-27 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('netlink', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=20)),
                ('time_and_location', models.CharField(max_length=40)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Consultant')),
            ],
            options={
                'unique_together': {('time_and_location', 'consultant')},
            },
        ),
    ]
