# Generated by Django 3.0.4 on 2020-03-30 22:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_auto_20200329_2208'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastShift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=20)),
                ('time_and_location', models.CharField(max_length=40)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notifier.Consultant')),
            ],
            options={
                'ordering': ('date', 'start_time'),
                'unique_together': {('time_and_location', 'consultant')},
            },
        ),
    ]
