# Generated by Django 3.0.4 on 2020-03-31 20:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0003_pastshift'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pastshift',
            options={'ordering': ('date', 'start')},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'ordering': ('date', 'start')},
        ),
        migrations.RenameField(
            model_name='pastshift',
            old_name='end_time',
            new_name='end',
        ),
        migrations.RenameField(
            model_name='pastshift',
            old_name='start_time',
            new_name='start',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='start_time',
        ),
        migrations.AddField(
            model_name='shift',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shift',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shift',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
